[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
game = "3QfKEYFr6fgT1oc2wjptWMQoB6Qf96PPKqzutPQqUrz2"
play = "9nb1AEZzVaC1VvoQAUoDJTuZK3x2uZDQ2cZd3tuAQwzC"
counter = "coUnmi3oBUtwtd9fjeAvSsJssXh5A5xyPbhpewyzRVF"
credit = "H1kXTuAJntnCELS2phbS7bMcD4VYy5CQK3wKFC9BMgfL"
item = "3BjKmutGGbVtnVeeJnNg9xKqkAticq7WYvBjuBr1dQab"
shop = "CR8Sox2FniGkNFQ6AmE7FGi5cJjpJn7QTvhhgZcbg9PX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
